[package]
name = "webcryptobox"
version = "1.0.0"
license = "Apache-2.0"
edition = "2021"
description = "Webcryptobox provides convenient wrappers around OpenSSL to use WebCrypto compatible cryptography."

[dependencies]
openssl = "0.10.38"
hex = "0.4.3"
base64 = "0.13.0"
